### PR TITLE
Mread upgrade to akka 2.6.x

### PR DESCRIPTION
**Pull request by michael-read**
Includes security changes associated with PR - https://github.com/doriordan/skuber/pull/312.

Upgrade to Akka 2.6.8, Akka Http 10.1.12, Mockito 3.4.4

### CODE REVIEW

**Comment by michael-read** [comment]
The examples : [5] & [6] don't work properly... but behavior matches the existing `master`.

**Comment by michael-read** [comment]
This PR drops support for Scala 2.11.

**Comment by doriordan** [comment]
Thanks for this - I'll review as soon as possible, the plan is to cut a final release on current platform first, and then update to Akka 2.6.x via this PR.

**Comment by RayRoestenburg** [comment]
Hi @doriordan any idea when a version of skuber updated to Akka 2.6.x can be cut?

**Comment by doriordan** [comment]
Hi @RayRoestenburg some other things have kept me busy but I am looking at this now

**Comment by doriordan** [comment]
LGTM thanks (sorry it took a while)

**Comment by RayRoestenburg** [comment]
@doriordan Thanks! Would be great to get #317 and #312 also reviewed, can you have a look? We're looking forward to a a next release :-)

**Pull request merged**
