### PR TITLE
Updated Scala version 2.13, fixed compilation issues after the update

### PR DESCRIPTION
**Pull request by psisoyev**

### CODE REVIEW

**Comment by doriordan** [comment]
Thanks for the PR @psisoyev, I am looking at this now

**Comment by doriordan** [comment]
I found some additional changes were needed for successful build/test, as follows:
- sbt version in `project/build.properties` needs updating for Scala 2.13 support
- several of the integration tests under `client/src/it` need modification due to use of postfix operators (you had already fixed this in other classes)
- Use of `view.mapValues` not supported on 2.11 or 2.12 (cross-compilation), modified to use a straight `map` instead.

I addressed these and pushed the updates to https://github.com/doriordan/skuber/tree/scala-2.13

It is up to you whether you want to cherry pick my commits from that branch into yours and push the updates back to this PR, or I can create a new PR - let me know...thanks!

**Comment by psisoyev** [comment]
Ah yes, actually I forgot to push the SBT version update. You can freely create a new PR and cherry pick the stuff. Cheers!

**Comment by doriordan** [comment]
OK thanks I will close this PR and push another one - thanks for the contributions

**Pull request closed without merging**
