### PR TITLE
moving Ingress into networking with apiVersion=networking.k8s.io/v1beta1

### PR DESCRIPTION
**Pull request by yurique**
* making Ingress backend port a string (to use the service port name instead of int value)
* some tweaks to CronJob and ConfigMap
* dependency bumps

### CODE REVIEW

**Comment by yurique** [comment]
will be happy to do any tweaks here if I got something wong

**Comment by metasim** [comment]
@doriordan Would you be open to releasing and update with this fix in it?

**Comment by Krever** [comment]
I would be interested in this as well.

**Comment by doriordan** [comment]
LGTM - thanks for the PR (and apologies for delay)

**Pull request merged**
