### PR TITLE
Update library versions

### PR DESCRIPTION
**Pull request by janstenpickle**
- update akka-http, scalacheck, specs2, scalatest, snakeyaml, commons-io, bouncycastle, akka-slf4j, and play-json
- add depenedency on akka-stream, which is no longer provided by akka-http

### CODE REVIEW

**Comment by ngortheone** [comment]
Hi @janstenpickle 
I'm just curious what is the motivation updating dependencies versions?

**Comment by doriordan** [comment]
Hi @janstenpickle -apologies but I just came to reviewing this PR now, but coincidentally  I updated the key Akka dependencies in #178 (created and merged today before I saw your PR). 
My motivation was partly the normal good practice of keeping key dependencies up to date, but also because I need some of the newer Akka streams functionality for something else I am working on.
The other dependency updates in this PR are probably worth doing as well, but unfortunately you'll need to rebase.

**Comment by janstenpickle** [comment]
@doriordan no problem at all, thanks for taking a look! I've just rebased against your changes, so it should be mergable again now.

**Comment by ngortheone** [comment]
@janstenpickle it appears that my fix of spec2 created a merge conflict again

**Comment by doriordan** [comment]
My fault - I left merging this for too long. 
@janstenpickle if you can rebase again I'll merge thanks

**Comment by janstenpickle** [comment]
@doriordan sorted

**Comment by doriordan** [comment]
LGTM thanks

**Pull request merged**
