### PR TITLE
Refactor patch method

### PR DESCRIPTION
**Pull request by dtaniwaki**
I removed `jsonMergePatch` method as the functionality is covered by `patch` method and keeping it will confuse developers. I also made a bug fix of `sealed trait` issue and some refactoring.

### CODE REVIEW

**Comment by dtaniwaki** [comment]
I saw your comment of https://github.com/doriordan/skuber/pull/236#issuecomment-434628822 but I'd like to ask you to add this PR as well because it has a bug fix of https://github.com/doriordan/skuber/pull/237/commits/8d420fc3da11250843d57e0a9b3030ce4b88be5a. Or, at least please cherry-pick the commit. Otherwise, we can't make custom patch classes.

**Comment by doriordan** [comment]
@dtaniwaki I think it better to keep `jsonMergePatch` for the moment for backwards compatibility, it probably should be marked as @deprecated from the 2.1 release though and removed later.

Can you update this PR by removing all commits except  https://github.com/doriordan/skuber/commit/8d420fc3da11250843d57e0a9b3030ce4b88be5a (and renaming it) or else just raise a new PR with just that commit if easier? Happy to merge that change for `2.0.12`

**Comment by dtaniwaki** [comment]
Thank you for including the fix in the release. I'll update the PR right now.

What do you think about the refactoring of
https://github.com/doriordan/skuber/pull/237/commits/b2d8ad4cf09cd6b7ce38bfc4c60a363f3deb3427 ?

**Comment by dtaniwaki** [comment]
I don’t mind reverting the other changes except the one you suggested, but could you give me your thought about the changes I made?

**Comment by dtaniwaki** [comment]
Did it in https://github.com/doriordan/skuber/pull/240, thanks!

**Comment by doriordan** [comment]
@dtaniwaki as expected, this now needs a rebase after the merge to master of the 2.1 refactor

**Pull request closed without merging**
